### ISSUE TITLE
Haproxy configuration for proxy `vector` is not usable

### ISSUE THREAD

**Issue by roumigus** [vectordotdev/helm-charts#112]
### Two bugs in one

* The current default haproxy configuration of the proxy named `vector` is not usable.
* Currently the default values `vectorSource.enabled: true` and `vectorSource.listenPort: 9000` are flagged as "deprecated", but still they would break the haproxy config for an hypothetical user with `haproxy.enabled: true` and who happened to choose randomly `9000` as a port  in `service.ports`.

#### example 1

This in the values.yaml:
```yaml
vectorSource:
  enabled: true
  listenPort: 9000

service:
  ports:
    - name: agent
      port: 9000
      protocol: TCP
      targetPort: 9000

haproxy:
  enabled: true
```

Would create two frontend binding on the same port 9000 in haproxy config:
```
frontend vector
  bind :::9000 proto h2
  mode http
  [...]

backend vector
  mode http
  [...] (backend proto h2)

frontend agent
  bind :::9000
  (default/implied: mode tcp)
  [...]

backend agent
  (default/implied: mode tcp)
  [...] (backend proto tcp)
```

Haproxy starts, but the requests ends randomly in one or the other frontend, making it an erratic loadbalancer.

#### example 2

This configuration looks fine at a first glance:
```yaml
# I only have one source/port to expose: fluent (no vector source)
service:
  ports:
    - name: fluent
      port: 9000
      protocol: TCP
      targetPort: 9000

haproxy:
  enabled: true
```

But it would create a conflict in haproxy (see above), messing up with the unrelated `fluent` source. This config just needs a `vectorSource.enabled: false`, but maybe we could document this somewhere. Most users would assume that a vectorSource "deprecated" option won't mess with their loadbalancing config, and the errors are hard to catch, since haproxy actually do starts. The only way to understand why we're missing some logs is to read thoughtfully the haproxy logs.

### Detailed explanation
[This part](https://github.com/vectordotdev/helm-charts/blob/vector-aggregator-0.18.1/charts/vector-aggregator/templates/haproxy/_helpers.tpl#L47-L59) relies on values from the deprecated `vectorSource` from [here in values.yaml](https://github.com/vectordotdev/helm-charts/blob/vector-aggregator-0.18.1/charts/vector-aggregator/values.yaml#L285-L301).

I assume that in the past, this block was used to generate:
* a source `vector` configuration for the vector instance
* the kubernetes service with the port from `vectorSource.listenPort` ([default 9000](https://github.com/vectordotdev/helm-charts/blob/vector-aggregator-0.18.1/charts/vector-aggregator/values.yaml#L294))
* the haproxy proxy configuration `vector` (frontend and backend), with mode http

Now, the haproxy `vector` proxy config is still generated (that is, as long as `vectorSource.enabled` [is true](https://github.com/vectordotdev/helm-charts/blob/vector-aggregator-0.18.1/charts/vector-aggregator/templates/haproxy/_helpers.tpl#L47)), however we configure the `vector` source in `customConfig` instead ([here](https://github.com/vectordotdev/helm-charts/blob/vector-aggregator-0.18.1/charts/vector-aggregator/values.yaml#L223-L226)), and since no kubernetes service is generated automatically anymore, we need to populate `service` [as well](https://github.com/vectordotdev/helm-charts/blob/vector-aggregator-0.18.1/charts/vector-aggregator/values.yaml#L204-L205) in order for our `source` to be reachable on its port.

As a result, when configuring a vector `source`, [the generic haproxy proxy config](https://github.com/vectordotdev/helm-charts/blob/vector-aggregator-0.18.1/charts/vector-aggregator/templates/haproxy/_helpers.tpl#L60-L70) is generated as well (looping over the `service` values)

This generic proxy configuration has different options compared to the default `vector` one (default `mode tcp` instead of `mode http` + `proto h2`. See also [this PR](https://github.com/vectordotdev/helm-charts/pull/94/files) for context). If we want a proper HTTP config for a vector sink <-> source communitation, we have no other choice but to override the whole haproxy config [here](https://github.com/vectordotdev/helm-charts/blob/vector-aggregator-0.18.1/charts/vector-aggregator/values.yaml#L463-L493).

Keeping the haproxy `vector` proxy configuration and use the port from `vectorSource.listenPort` is not an option due to how the chart works currently. We would need to define a service in `service.ports` with a port equal to `values.vectorSource.listenPort`, but then we would end up with two frontend binding on the same port: one at the [default vector proxy level](https://github.com/vectordotdev/helm-charts/blob/vector-aggregator-0.18.1/charts/vector-aggregator/templates/haproxy/_helpers.tpl#L49) and one at the proxy [generated iteratively](https://github.com/vectordotdev/helm-charts/blob/vector-aggregator-0.18.1/charts/vector-aggregator/templates/haproxy/_helpers.tpl#L62) for each elements in `service.ports`. While not an invalid configuration from haproxy POV (it will start), this would be make for a non sensical configuration: connecting randomly to different frontends.

Maybe we can think of a way to provide a default sane haproxy block config for a basic vector sink <-> source configuration. We could also document that this config works only for vector sink/source in v2 (gRPC over HTTP2). It should be easy to enable for new users, while not preventing users from overriding it.

Would anyone be interested in a PR to change this part or the chart ? Or was there a plan to drop this default haproxy `vector` proxy configuration ?

**Comment by spencergilbert** [comment]
Hey @roumigus thanks for the detailed bug report! I definitely didn't catch this myself and I'm sorry you ran into it. As you noted those options are deprecated, and if you've missed it we're also phasing out the `vector-aggregator` (and `vector-agent`) charts for the new [`vector` chart](https://github.com/vectordotdev/helm-charts/#vector-helm-charts).

The new chart has much less generation of the HAProxy config, but a broader set of defaults, which I believe should avoid this same bug occurring.

I'd be happy to accept a PR fixing the bug in the deprecated charts if you're staying on the old charts for the near future.

**Comment by spencergilbert** [comment]
As the related chart has been deprecated, I'm going to close this issue out.
