### ISSUE TITLE
Seeing rate limited warnings when using adaptive concurrency with Loki sink.

### ISSUE THREAD

**Issue by sam-mcbr** [vectordotdev/helm-charts#127]
Wanted to link the [vector issue](https://github.com/vectordotdev/vector/issues/10364) here in case it is a bug with the chart and not vector itself.

**Comment by spencergilbert** [comment]
I'm 99% sure it's with Vector itself but we can leave it open for now 👍

**Comment by jszwedko** [comment]
Closing in-lieu of https://github.com/vectordotdev/vector/issues/10364 since this is unlikely to be an issue with the helm chart.
