### ISSUE TITLE
"http2 error: connection error detected: frame with invalid size" for vector sink when ngnix ingress is used. 

### ISSUE THREAD

**Issue by vpradeepkum** [vectordotdev/helm-charts#143]
Here is my deployment model. 

onperm servers with vector agent --> GKE ngnix with default config -> ha proxy -> vector aggregator.

Internal IT will allow only port 443 to reach any GCP resources. Hence we are forced to go with ingress and port to fqdn mapping has been made accordingly. 

Note: traffic works fine if i bypass firewall ( which eliminates the need of ingress) or attach loadbalancer to ha proxy directly. 

when we start the agent, traffic fails with below error. 

```
2022-01-10T21:37:26.588163Z  WARN sink{component_kind="sink" component_id=my_sink_id component_type=vector component_name=my_sink_id}:request{request_id=1}: vector::sinks::util::retries: Retrying after error. error=Request failed: status: Unknown, message: "http2 error: connection error detected: frame with invalid size", details: [], metadata: MetadataMap { headers: {} }

Agent config: 

sources:
  file_log:
    type: file
    acknowledgements: true
    ignore_older_secs: 600
    include:
      - /Users/Downloads/vector/*.log
    read_from: beginning
sinks:
  my_sink_id:
    type: vector
    inputs: ["file_log"]
    #send_buffer_bytes: 65536
    address: dc-log-stream:443
    buffer:
      type: memory
      when_full: block
      #max_size: 104900000
      #max_size: 500
      max_events: 500
    #send_buffer_bytes: 65536
    healthcheck: false
    version: "2"
    tls:
      enabled: true



**Aggregator :**

customConfig:
  data_dir: /vector-data-dir
  api:
    enabled: true
    address: 127.0.0.1:8686
    playground: true
  sources:
    vector:
      address: 0.0.0.0:6000
      type: vector
      version: "2"
    dc-metric:
      type: vector
      acknowledgements: true
      address: "0.0.0.0:9002"
      version: "2"
      tls:
        enabled: false
    dc-log:
      type: vector
      acknowledgements: true
      address: "0.0.0.0:9003"
      #receive_buffer_bytes: 1e+08
      version: "2"
      tls:
        enabled: false
  sinks:
    stdout:
      type: console
      inputs: [dc-log]
      encoding:
        codec: json
    push_loki_baremetal_logs:
      type: loki
      inputs: [ "dc-log" ]
      #inputs: ["remap"]
      endpoint: "http://loki:3100"
      encoding:
        codec: json
        timestamp_format: "rfc3339"
      out_of_order_action: rewrite_timestamp
      healthcheck: true
      remove_label_fields: false
      request:
        # https://vector.dev/blog/adaptive-request-concurrency/
        concurrency: "adaptive"
      labels:
        #event: "{{ event_field }}"
        forwarder: vector
        #host: "{{ host }}"
        #file: "{{ file }}"


can you please add the default config to be added to ngnix to support vector to vector communication.

**Comment by spencergilbert** [comment]
It sounds like your NGINX may not be configured to support gRPC traffic. Can you share the config you've used?

**Comment by vpradeepkum** [comment]
@spencergilbert .. Attaching the discussion which we had it in discord for reference. 

![Uploading image.png…]()

**Comment by vpradeepkum** [comment]
Spencer
 — 
Yesterday at 2:11 PM
You can probably just go from GKE NGINX directly to the Aggregators, but it sounds like the NGINX may not be configured to receive gRPC traffic?
Can you share the ingress resource?
harshavpk
 — 
Yesterday at 2:25 PM
@Spencer .. here is the ingress resource:

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    field.cattle.io/publicEndpoints: '[{"addresses":["10.1.2.85"],"port":443,"protocol":"HTTPS","serviceName":"stream-vector:vector-aggregator-haproxy","ingressName":"stream-vector:vector-aggregator","hostname":"dc-log-stream.stream.core.stream.local","path":"/*","allNodes":false},{"addresses":["10.1.2.85"],"port":443,"protocol":"HTTPS","serviceName":"stream-vector:vector-aggregator-haproxy","ingressName":"stream-vector:vector-aggregator","hostname":"dc-metric-stream.stream.core.stream.local","path":"/*","allNodes":false}]'
    kubernetes.io/ingress.class: nginx

Expand
ingress.yaml4 KB
Spencer
 — 
Yesterday at 2:26 PM
It looks like it's missing an annotation to tell to setup for gRPC. You can set that with nginx.ingress.kubernetes.io/backend-protocol https://kubernetes.github.io/ingress-nginx/examples/grpc/#step-3-create-the-kubernetes-ingress-resource-for-the-grpc-app
harshavpk
 — 
Yesterday at 2:30 PM
Thanks @Spencer .. let me quickly try with this annotation.
Spencer
 — 
Yesterday at 2:34 PM
I'd definitely recommend just using the NGINX ingress and not include the HAProxy, it'll just add additional latency for no benefit
harshavpk
 — 
Yesterday at 2:44 PM
sure @Spencer .. i will try without HA proxy. Also i tried with grpc annotation but still having the same issue. i will disable the HA proxy and will quickly check.
harshavpk
 — 
Today at 9:49 AM
@Spencer .. unfortunately annotation didnt help with or without haproxy.
not sure if we are running into similar problem.
https://kennethjenkins.net/posts/go-nginx-grpc/
A misleading error when using gRPC with Go and nginx
I wanted to document an issue I ran into while trying to write a gRPC service in Go, in case someone else just so happens to run into the same problem.
The scenario was this:
 I had a web service written in Go serving both HTTP traffic and gRPC traffic in plaintext on the same port using nginx as a reverse proxy to provide TLS.  This might seem ...
here is the list of annotation which i used 


annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.org/grpc-services: "vector-aggregator dc-log"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.org/client-max-body-size: 100m

**Comment by spencergilbert** [comment]
Can you share the logs from a NGINX pod that's handling the request?

**Comment by draveness** [comment]
I met the same issue with similar ingress and vector config

```
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.org/client-max-body-size: 100m
```

nginx log

```
10.4.1.1 - - [26/Apr/2022:18:09:29 +0000] "PRI * HTTP/2.0" 400 150 "-" "-" 0 0.098 [] [] - - - - dffa75aaa47af7a5e7e487a5b772602b
10.4.1.1 - - [26/Apr/2022:18:09:35 +0000] "PRI * HTTP/2.0" 400 150 "-" "-" 0 0.097 [] [] - - - - bd9c804b896c47ff111e0c8f2a021964
10.4.1.1 - - [26/Apr/2022:18:09:43 +0000] "PRI * HTTP/2.0" 400 150 "-" "-" 0 0.098 [] [] - - - - 09e760d39c397baa1180c1f7c5e30f9e
10.4.1.1 - - [26/Apr/2022:18:09:57 +0000] "PRI * HTTP/2.0" 400 150 "-" "-" 0 0.099 [] [] - - - - eb2c4dc7256fe09230ae84609f7cfef2
10.4.1.1 - - [26/Apr/2022:18:10:18 +0000] "PRI * HTTP/2.0" 400 150 "-" "-" 0 0.102 [] [] - - - - 30861d2d1d4b5c5a94538052da742ea4
```

**Comment by spencergilbert** [comment]
This _may_ be on the nginx side: https://github.com/kubernetes/ingress-nginx/issues/5886

**Comment by draveness** [comment]
I tried to switch to version 1 on both agent and aggregator

```
agent:
2022-04-27T07:54:41.800674Z ERROR sink{component_kind="sink" component_id=vector_aggr component_type=vector component_name=vector_aggr}: vector::internal_events::tcp: TCP socket error. error=Broken pipe (os error 32) error_code="socket_failed" error_type="writer_failed" stage="sending" internal_log_rate_secs=10

aggregator
2022-04-27T07:57:20.964794Z  WARN source{component_kind="source" component_id=vector component_type=vector component_name=vector}:connection{peer_addr=10.4.1.73:38610}: vector::internal_events::decoder: Failed framing bytes. error=frame size too big internal_log_rate_secs=10
```

config

```
[sinks.vector_aggr]
type = "vector"
inputs = [ "parse_logs" ]
address = ".....:80"
version = "1"
buffer.max_events = 5
```

```
vector:
  image:
    tag: 0.21.1-debian
  customConfig:
    api:
      enabled: true
      address: 127.0.0.1:8686
      playground: false
    sources:
      vector:
        address: 0.0.0.0:6000
        type: vector
        version: "1"
    sinks:
      stdout:
        type: console
        inputs: ["vector"]
        encoding:
          codec: json
```

**Comment by draveness** [comment]
I use http on both source and sink side to bypass this issue

**Comment by kadhriesh** [comment]
@draveness can you share me example config with http source and sink I am trying with ingress.but my question is can we forward data comming 80 port and forward to vector service
