### ISSUE TITLE
Inconsistency between .Values.existingConfig and .Values.existingConfigMaps

### ISSUE THREAD

**Issue by wtchangdm** [vectordotdev/helm-charts#181]
Hi, I was checking the vector chart before trying it out. However, I noticed the change that updated `existingConfig` to `existingConfigMaps` in https://github.com/vectordotdev/helm-charts/commit/17c94b8cbf21e6b1f1dedf329f74f8b928be5d46 seem not modified on some files.

For example: 

- https://github.com/vectordotdev/helm-charts/blob/develop/charts/vector/templates/configmap.yaml#L1
- https://github.com/vectordotdev/helm-charts/blob/develop/charts/vector/templates/service-headless.yaml#L15
- https://github.com/vectordotdev/helm-charts/blob/develop/charts/vector/templates/service.yaml#L14

**Comment by spencergilbert** [comment]
Thanks for catching this @wtchangdm !

**Comment by wtchangdm** [comment]
Thank you @spencergilbert! I haven't looked into the haproxy settings, thanks for fixing it as well.
