### ISSUE TITLE
how to receive data in pods?

### ISSUE THREAD

**Issue by caibirdme** [vectordotdev/helm-charts#200]
If I install vector as daemonset(not sidecar) in k8s cluster, how could vector receive log data in pods on the same node? I don't find any documentation about this. Or if I try to send logs to vector aggregator, what's the protocol should be, what's the endpoint? I cannot find document about that either? Can anyone help?

**Comment by spencergilbert** [comment]
See the answer [here](https://github.com/vectordotdev/vector/discussions/12254#discussioncomment-2578243). You can also review the documentation [here](https://vector.dev/docs/reference/configuration/sources/kubernetes_logs/#how-it-works) or the original [RFC](https://github.com/vectordotdev/vector/blob/master/rfcs/2020-04-04-2221-kubernetes-integration.md).
