### ISSUE TITLE
vector _pod.tpl does not allow hostNetwork

### ISSUE THREAD

**Issue by mdaniel** [vectordotdev/helm-charts#213]
For clusters with `--http-put-response-hop-limit 1` on purpose, we need to run vector with `hostNetworking: true` so it can run the `aws_ec2_metadata` transform without exposing IMDSv2 to the workload Pods

The [current `_pod.tpl`](https://github.com/vectordotdev/helm-charts/blob/develop/charts/vector/templates/_pod.tpl) does not offer `.Values.hostNetwork` or such that would allow the chart to be installed in that configuration

**Comment by spencergilbert** [comment]
I think I've always seen us recommend upping the hop-limit, but I'm sure there's cases where that's not desired.

Easy to add in, happy to review a contribution otherwise I've added it to our backlog!

**Comment by rgl** [comment]
@spencergilbert please take a look at #238 and let me known if something is missing :-)
