### ISSUE TITLE
vector _pod.tpl does not offer envFrom

### ISSUE THREAD

**Issue by mdaniel** [vectordotdev/helm-charts#214]
We have an existing `Secret` that would be very handy for providing to vector just like we provide it to other workloads, but the [current `_pod.tpl`](https://github.com/vectordotdev/helm-charts/blob/develop/charts/vector/templates/_pod.tpl) only accepts `.Values.env`, wherein we have to unpack the keys using `secretKeyRef`

I wanted to bring that missing `envFrom` to your attention

**Comment by spencergilbert** [comment]
Ah - easy enough to add in, I feel like I remembered that being under the same `env` key 🤔 

I'll look to add this in when I get a chance, otherwise happy to accept a contribution.
