### ISSUE TITLE
Custom Lua code as ConfigMap

### ISSUE THREAD

**Issue by NasAmin** [vectordotdev/helm-charts#216]
Hi,

I am having to write custom Lua code to change metrics type. I would like to write this code in separate files and write some tests for them.
However, I am not sure how to tell the helm chart to mount those files to the vector agent.  What would be the best way to achieve this?

I am looking at [this doc](https://vector.dev/docs/reference/configuration/transforms/lua/#search-directories)

I'll appreciate any help, thanks a lot!

**Comment by spencergilbert** [comment]
Hi @NasAmin,

`extraVolumeMounts` and `extraVolumes` can be used to include arbitrary volumes (including ConfigMaps) in the Vector Pod.

Let me know if that covers your need.

**Comment by NasAmin** [comment]
That worked great -- thanks a lot!
