### ISSUE TITLE
Enable reloading of config for aggregator

### ISSUE THREAD

**Issue by sinacek** [vectordotdev/helm-charts#281]
Enable reloading of config for aggregator when config file is changed without restart of pod. 

Notes: 
- https://vector.dev/docs/administration/management/#reloading
- https://github.com/jimmidyson/configmap-reload

**Comment by sinacek** [comment]
Hi @jszwedko , that is exactly how you described. Roadmap of which project do you mean?

**Comment by jszwedko** [comment]
> Hi @jszwedko , that is exactly how you described. Roadmap of which project do you mean?

The roadmap of the https://github.com/jimmidyson/configmap-reload project. It looks like they aim to support sending SIGHUPs in the future which means it'll just work with Vector. Assuming that is what you want, I think we can close this issue and just wait for them to add it (https://github.com/jimmidyson/configmap-reload/issues/23).

**Comment by sinacek** [comment]
That issue is 5 years old, so i'm not sure if he has plan to implement it. Do you have on road map add endpoint to reload as it has prometheus?

**Comment by jszwedko** [comment]
We don't have plans for that at the moment, but if it'd be useful for you would you want to open a feature request on the Vector repository describing what you would need? https://github.com/vectordotdev/vector/issues/new?assignees=&labels=type%3A+feature&template=feature.yml

**Comment by sinacek** [comment]
I find that similar issue is already exists, so I send comment there https://github.com/vectordotdev/vector/issues/541

**Comment by jszwedko** [comment]
Thanks! On first read it seems like this is a reasonable approach but cc/ @vectordotdev/vector for additional thoughts.
