### ISSUE TITLE
Changing to debug does not take effect

### ISSUE THREAD

**Issue by baiyibing123** [vectordotdev/helm-charts#359]
<img width="776" alt="image" src="https://github.com/vectordotdev/helm-charts/assets/14048464/193dc301-f511-4ce4-ae3d-fc824101c026">
Changing to debug does not take effect

<img width="1427" alt="image" src="https://github.com/vectordotdev/helm-charts/assets/14048464/d5e642ed-7684-4cc0-9904-29bfa0e73e1b">

**Comment by jszwedko** [comment]
Good catch. I opened a PR to fix this here: https://github.com/vectordotdev/helm-charts/pull/362

**Comment by baiyibing123** [comment]
When can I use it

**Comment by jszwedko** [comment]
> When can I use it

The next release, which is TBD.
