### ISSUE TITLE
Update PodDisruptionBudget api version

### ISSUE THREAD

**Issue by spencergilbert** [vectordotdev/helm-charts#97]
```
Warning: policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
```

**Comment by mehta-ankit** [comment]
@spencergilbert Hello 👋🏽 
Is there a possibility we can try to use bitnami's common chart to use stuff like this: https://github.com/bitnami/charts/blob/master/bitnami/common/templates/_capabilities.tpl#L21

**Comment by spencergilbert** [comment]
@mehta-ankit that's an interested discussion - but chatting with the team we'd prefer to not add any dependencies at this time. Thanks for the suggestion!
